/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Pattern = IDL.Record({
  'bpm' : IDL.Float64,
  'name' : IDL.Text,
  'stepDataJson' : IDL.Text,
  'swing' : IDL.Float64,
});
export const Preset = IDL.Record({
  'paramsJson' : IDL.Text,
  'mode' : IDL.Text,
  'name' : IDL.Text,
});
export const Snapshot = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'engineStateJson' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'deletePattern' : IDL.Func([IDL.Text], [], []),
  'deletePreset' : IDL.Func([IDL.Text], [], []),
  'deleteSnapshot' : IDL.Func([IDL.Nat], [], []),
  'getAllPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
  'getAllPresetsByMode' : IDL.Func([IDL.Text], [IDL.Vec(Preset)], ['query']),
  'getAllSnapshots' : IDL.Func([], [IDL.Vec(Snapshot)], ['query']),
  'getPattern' : IDL.Func([IDL.Text], [Pattern], ['query']),
  'getPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
  'getSnapshot' : IDL.Func([IDL.Nat], [Snapshot], ['query']),
  'savePattern' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'savePreset' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveSnapshot' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'updateSnapshot' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Pattern = IDL.Record({
    'bpm' : IDL.Float64,
    'name' : IDL.Text,
    'stepDataJson' : IDL.Text,
    'swing' : IDL.Float64,
  });
  const Preset = IDL.Record({
    'paramsJson' : IDL.Text,
    'mode' : IDL.Text,
    'name' : IDL.Text,
  });
  const Snapshot = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'engineStateJson' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'deletePattern' : IDL.Func([IDL.Text], [], []),
    'deletePreset' : IDL.Func([IDL.Text], [], []),
    'deleteSnapshot' : IDL.Func([IDL.Nat], [], []),
    'getAllPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
    'getAllPresetsByMode' : IDL.Func([IDL.Text], [IDL.Vec(Preset)], ['query']),
    'getAllSnapshots' : IDL.Func([], [IDL.Vec(Snapshot)], ['query']),
    'getPattern' : IDL.Func([IDL.Text], [Pattern], ['query']),
    'getPreset' : IDL.Func([IDL.Text], [Preset], ['query']),
    'getSnapshot' : IDL.Func([IDL.Nat], [Snapshot], ['query']),
    'savePattern' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'savePreset' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveSnapshot' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
    'updateSnapshot' : IDL.Func([IDL.Nat, IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };