/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Pattern {
  'bpm' : number,
  'name' : string,
  'stepDataJson' : string,
  'swing' : number,
}
export interface Preset {
  'paramsJson' : string,
  'mode' : string,
  'name' : string,
}
export interface Snapshot {
  'id' : bigint,
  'name' : string,
  'engineStateJson' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'deletePattern' : ActorMethod<[string], undefined>,
  'deletePreset' : ActorMethod<[string], undefined>,
  'deleteSnapshot' : ActorMethod<[bigint], undefined>,
  'getAllPatterns' : ActorMethod<[], Array<Pattern>>,
  'getAllPresetsByMode' : ActorMethod<[string], Array<Preset>>,
  'getAllSnapshots' : ActorMethod<[], Array<Snapshot>>,
  'getPattern' : ActorMethod<[string], Pattern>,
  'getPreset' : ActorMethod<[string], Preset>,
  'getSnapshot' : ActorMethod<[bigint], Snapshot>,
  'savePattern' : ActorMethod<[string, string, number, number], undefined>,
  'savePreset' : ActorMethod<[string, string, string], undefined>,
  'saveSnapshot' : ActorMethod<[string, string, bigint], bigint>,
  'updateSnapshot' : ActorMethod<[bigint, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];