/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Snapshot {
    id: bigint;
    name: string;
    engineStateJson: string;
    timestamp: bigint;
}
export interface Preset {
    paramsJson: string;
    mode: string;
    name: string;
}
export interface Pattern {
    bpm: number;
    name: string;
    stepDataJson: string;
    swing: number;
}
export interface backendInterface {
    deletePattern(name: string): Promise<void>;
    deletePreset(name: string): Promise<void>;
    deleteSnapshot(id: bigint): Promise<void>;
    getAllPatterns(): Promise<Array<Pattern>>;
    getAllPresetsByMode(mode: string): Promise<Array<Preset>>;
    getAllSnapshots(): Promise<Array<Snapshot>>;
    getPattern(name: string): Promise<Pattern>;
    getPreset(name: string): Promise<Preset>;
    getSnapshot(id: bigint): Promise<Snapshot>;
    savePattern(name: string, stepDataJson: string, bpm: number, swing: number): Promise<void>;
    savePreset(name: string, mode: string, paramsJson: string): Promise<void>;
    saveSnapshot(name: string, stateJson: string, timestamp: bigint): Promise<bigint>;
    updateSnapshot(id: bigint, newStateJson: string, newTimestamp: bigint): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deletePattern(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePattern(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePattern(arg0);
            return result;
        }
    }
    async deletePreset(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreset(arg0);
            return result;
        }
    }
    async deleteSnapshot(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSnapshot(arg0);
            return result;
        }
    }
    async getAllPatterns(): Promise<Array<Pattern>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatterns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatterns();
            return result;
        }
    }
    async getAllPresetsByMode(arg0: string): Promise<Array<Preset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPresetsByMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPresetsByMode(arg0);
            return result;
        }
    }
    async getAllSnapshots(): Promise<Array<Snapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSnapshots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSnapshots();
            return result;
        }
    }
    async getPattern(arg0: string): Promise<Pattern> {
        if (this.processError) {
            try {
                const result = await this.actor.getPattern(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPattern(arg0);
            return result;
        }
    }
    async getPreset(arg0: string): Promise<Preset> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreset(arg0);
            return result;
        }
    }
    async getSnapshot(arg0: bigint): Promise<Snapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getSnapshot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSnapshot(arg0);
            return result;
        }
    }
    async savePattern(arg0: string, arg1: string, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePattern(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePattern(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async savePreset(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePreset(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePreset(arg0, arg1, arg2);
            return result;
        }
    }
    async saveSnapshot(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSnapshot(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSnapshot(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSnapshot(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSnapshot(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSnapshot(arg0, arg1, arg2);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
